#!/usr/bin/env bash
# $1 - domain
# $2 - root url

wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --domains $1 \
     --no-parent \
     $2
