#!/usr/bin/env bash

cd ~/Downloads
wget -c http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.16-x86-64-linux-binary.tar.bz2
bzip2 -cd sbcl-1.2.16-x86-64-linux-binary.tar.bz2 | tar xvf -
cd sbcl-1.2.16-x86-64-linux
sudo sh install.sh
