#!/usr/bin/env bash

# Prints a random line file

if [ $# -ne 1  ]; then
    echo "usage: $0 <filename>"
    exit 1
fi

line_count=$(wc -l $1)
tokens=( $line_count )
line_count=${tokens[0]}

random_no=$(( 1 + $RANDOM % $line_count ))

sed -n "${random_no}p" $1

